name: Actualizar datos diarios

on:
  schedule:
    - cron: '0 0 * * *' # Esto ejecuta el flujo de trabajo diariamente a medianoche UTC
  workflow_dispatch: # Permite ejecutar el flujo de trabajo manualmente desde la interfaz de GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy matplotlib sendgrid

    - name: Run update script
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        python actualizar_datos.py
